Expand-Archive -Path "Y:\Applications\Reatores Quimicos\setup.zip" -DestinationPath "C:\Program Files" -Recurse -Force
New-Item -ItemType Directory -Path "C:\Users\Public\Desktop\Reatores Quimicos"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Ecology" -Value "C:\Program Files\Reatores Quimicos\Ecology\Ecology.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\EnzymeMan" -Value "C:\Program Files\Reatores Quimicos\EnzymeMan\EnzymeMan.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Great Race" -Value "C:\Program Files\Reatores Quimicos\Great Race\Great Race.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Heat Effects I" -Value "C:\Program Files\Reatores Quimicos\Heat Effects I\Heat Effects I.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Heat Effects II" -Value "C:\Program Files\Reatores Quimicos\Heat Effects II\Heat Effects II.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Heterogeneous Catalysis" -Value "C:\Program Files\Reatores Quimicos\Heterogeneous Catalysis\Heterogeneous Catalysis.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Kinetic Challenge I" -Value "C:\Program Files\Reatores Quimicos\Kinetic Challenge I\Kinetic Challenge I.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Kinetic Challenge II" -Value "C:\Program Files\Reatores Quimicos\Kinetic Challenge II\Kinetic Challenge II.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\MicroPlant" -Value "C:\Program Files\Reatores Quimicos\MicroPlant\MicroPlant.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Murder Mystery" -Value "C:\Program Files\Reatores Quimicos\Murder Mystery\Murder Mystery.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Staging" -Value "C:\Program Files\Reatores Quimicos\Staging\Staging.exe"
New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\Reatores Quimicos\Tic Tac Toe" -Value "C:\Program Files\Reatores Quimicos\Tic Tac Toe\Tic Tac Toe.exe"